USE employee(;
DELIMITER $$
CREATE FUNCTION AVG_MARK(MARK1 INT,MARK2 INT,MARK3 INT,MARK4 INT,MARK5 INT)
RETURNS INT
DETERMINISTIC
BEGIN
DECLARE TOTAL INT;
DECLARE AVERAGE float;
SET TOTAL = MARK1+MARK2+MARK3+MARK4+MARK5;
SET AVERAGE = TOTAL/5;
RETURN AVERAGE;
END $$
DELIMITER ;

SELECT AVG_MARK(10,20,30,40,50) AS AVERAGE;